
my_stopwords = c('empenh','empenha', 'empenhado', 'par','valor','dest','despes','fac','necess','pel',
                 'secretari','referent','destin','pagament','municipal','secret',"despesas","despesa",
                 'municipi','manutenca','faz','par','material', "anex","empenho",'fevereiro','marco',
                 "conform", "comum", "compr", "utiliz", "educaca", "divers","acima","aditivo",'abril',"mesa",
                 "contrat", "basic","assistenc","administraca","valor", "referente", "refa", "nº","nº","n°","nº",
                 "junt","nest","presencial","prega","realiz","ref","alun","referido","citado",'maio',"diaria","diarias", "dias",
                 "program","atend","ativ","saud","red","correspondente","concessao",'janeiro','junho','tesouro',
                 "not","unidad","fornec","social","uso","deste","consiste","realizar",'julho','administrativo','cidade',
                 "materi", "gener", "ser", "cam","servic","desenvolv","participar","proc","portaria",'financeiro',
                 "ensin", "compras", "compra", "genero", "generos","aplicavel","ordem",'agosto','memo',
                 "lote", "item", "piaui", "zona", "nao", "cor", "anexo", "edital", "especificacoes","folha",
                 "unid", "validade", "mgml", "conforme", "iii", "identificacao", "und","fundos","tecnico","tecnica",
                 "tipo", "prestacao", "unidades", "tamanho", "quadro", "execucao", "ano", "atender", "quantidade",
                 "litros", "grande", "cabo", "capacidade", 'registro', 'capacidade','mes','mensal',
                 'caixa', 'fornecimento', "municipio", "prefeitura", "secretaria", "aco", "embalagem", "empresa",
                 "administracao", "acordo", "afins", "agua", "alvespi","anexos", "assistencia","suprimento",
                 "ata", "atendimento", "atraves", "basica", "bens", "bombas", "brasileira",'novembro','meia','documento',
                 "campi", "campo", "centro", "chapeu", "colonia", "comuns", "condicoes","cidades","municipio","municipios","servico",
                 "parnaiba","amarante","capital","teresina","demerval","servico", "servicos", "servidor","prestados","prestado","servidores",
                 "confeccao", "constantes", "contidas","contrato", "demais", "demanda", "demandas",'tfdcampo',
                 "derivados", "desenvolvimeto", "deste", "desta", "destinado", "destinados",'silva',"recurso","recursos",
                 "estadual", "etc", "exercício", "exercicio", "exercicios", "visando",'outubro','maiorpimes',
                 "unidade", "trabalho", "termo", "teresina", "suprir", "sitiopi", "sistema","jose","fisica","gerais",
                 "serem", "sede", "reposicao", "referencia", "registrados", "deste", "eventual","estado",
                 "parcelado", "termo", "orgaos", "necessidades", "especializada", "manutencao","favor",
                 "materiais", "municipais", "precos", "secretarias", "uniao","relativo","autorizacao",
                 "secretario", "rocha", "rede", "realizacao", "quantitativos",'setembro',"auxiliar",
                 "quantidades", "publicos", "publica", "projetos", "programas", "preco","anexa","outros",
                 "prazo", "piripiri", "pessoa", "pertencentes", "parcelada","competencia","comarca",
                 "meio", "cozinha", "pertencentes", "loteii", "futura", "fuespi", "doze",'silva',
                 "durante", "nucleos", "presente", "futuras",'pagamento','periodo','dezembro',
                 'processo',"objeto", "licitacao", "geral", "consumo", "laboratorio", 'conf',
                 'pagamento','municip','face','atividad','nota','responsabilidad','programa','orgao',
                 'junto','destinada','fazer','materiai','necessidad')

######### SINONIMOS ######################

synonyms <- list(
  list(word="transporte", syns=c("deslocamento",
                                 "transportes",
                                 "trecho",
                                 "frete",
                                 "fretes",
                                 "passagens")),
  list(word="pagamento", syns=c("pago",
                                "pag",
                                "pagto",
                                "quinzena",
                                "credor",
                                "custear")),
  list(word="terceiros", syns=c("terceiro")),
  list(word="recurso", syns=c("recursos")),
  list(word="viagem", syns=c("diariaspassagens")),
  list(word="compra", syns=c("aquisicao",
                             "aquis",
                             "aquisição",
                             "abastec",
                             "abastecimento",
                             "aquisica",
                             "aquis",
                             "comp")),
  list(word="veiculo", syns=c("veiculos",
                              "automovel",
                              "onibus",
                              "fiat",
                              "uno",
                              "escavadeira",
                              "ford",
                              "moto",
                              "automotores",
                              "tratores",
                              "trator",
                              "automotor",
                              "frota",
                              "automoveis")),
  list(word="aluguel", syns=c("locacao",
                              "alugado")),
  list(word="justica", syns=c("juridica",
                              "juridico")),
  list(word="financeiro", syns=c("financeiros")),
  list(word="hospitalar", syns=c("odontologico",
                                  "saude",
                                  "medicamentos",
                                  "medicamento",
                                  "odontologica",
                                  "odontologicos",
                                  "vacina",
                                  "xarope",
                                  "medicao",
                                  "injecao",
                                  "seringa",
                                  "hospitalares",
                                  "fms",
                                  "lrpd",
                                  "medicos",
                                  "medico",
                                  "medicopsf",
                                  "medicoveterinario",
                                  "medico clinico",
                                  "medicoplantonista",
                                  "medicoesf",
                                  "alimentacao enteral",
                                  "material hospitalar",
                                  "funsaude",
                                  "funsaudesus",
                                  "enfermagem",
                                  "funsaudetesouro",
                                  "hospital")),
  list(word="obras", syns=c("construcao",
                            "reforma",
                            "ceramica",
                            "ceramicas",
                            "telhas",
                            "telha",
                            "civil",
                            "tijolo",
                            "tijolos",
                            "instalacao",
                            "instalacoes",
                            "eletrico",
                            "eletrica",
                            "eletricos",
                            "hidraulica",
                            "argamassa",
                            "arame",
                            "arames",
                            'predio',
                            "porta",
                            "cimento",
                            "pavimentacao",
                            "fechadura",
                            "rejunte",
                            "areia",
                            "broca de aco",
                            "pvc",
                            "pocos tubulares",
                            "poco tubular",
                            "hidraulico",
                            "lampada")),
  list(word="limpeza", syns=c("limepza",
                              "limpesa",
                              "higiene",
                              "sabao",
                              "higienizcao",
                              "higienizacao",
                              "desinfetante",
                              "soda caustica",
                              "agua sanitaria",
                              "limpezap",
                              "esponja de aco",
                              "palha de aco",
                              "hienizaca",
                              "desinf",
                              "detergente")),
  list(word="veiculo", syns=c("veiculos",
                              "automovel",
                              "onibus",
                              "fiat",
                              "uno",
                              "escavadeira",
                              "ford",
                              "moto",
                              "automotores",
                              "tratores",
                              "trator",
                              "automotor",
                              "frota",
                              "automoveis",
                              "etanol hidratado",
                              "combustiveis",
                              "combustivel",
                              "lubrax",
                              "etanol",
                              "gasolina",
                              "diesel",
                              "oleo diesel",
                              "querosene",
                              "lubrificante",
                              "graxa",
                              "biodiesel",
                              "gas",
                              "lubrificante",
                              "lubrificantes",
                              "ecombustiveis")),
  list(word="educacao", syns=c("curso",
                               "aula",
                               "material didatico",
                               "material grafico")),
  list(word="esporte", syns=c("esportivo",
                               "futebol",
                               "esportivos")),
  list(word="festividades", syns=c("materiais diversos",
                                    "festa",
                                    "comemoracao",
                                    "material diverso",
                                    "fogo de artificio",
                                    "plastico",
                                    "fogos de artificios")),
  list(word="vestuario", syns=c("camisa",
                                "camisas",
                                "calcao",
                                "calcoes",
                                "tecido",
                                "tecidos",
                                "meia",
                                "calca"))
)